# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_class',
            field=models.IntegerField(blank=True, choices=[(1, '甲'), (2, '乙'), (3, '丙'), (4, '丁')], null=True, verbose_name='班级'),
        ),
    ]
