# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curd', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobtitle',
            options={'verbose_name': '职称表', 'verbose_name_plural': '职称表'},
        ),
        migrations.AlterModelOptions(
            name='operatingarea',
            options={'verbose_name': '作业区表', 'verbose_name_plural': '作业区表'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': '职位表', 'verbose_name_plural': '职位表'},
        ),
        migrations.AlterModelOptions(
            name='profession',
            options={'verbose_name': '工种表', 'verbose_name_plural': '工种表'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '职工表', 'verbose_name_plural': '职工表'},
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='profession',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='profession',
            field=models.ManyToManyField(to='curd.Profession'),
        ),
    ]
